### ISSUE TITLE
MBrace.AWS or MBrace.Aws?

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.AWS#1]
The current projects are called MBrace.Aws but the project is called MBrace.AWS - it feels like MBrace.AWS is maybe better?  Any precedents here?

thx

**Comment by eiriktsarpalis** [comment]
Indeed, "Amazon" and "AWS" are being used, even in [type names](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/AWSConfigs.cs#L69).

**Comment by jimfoye** [comment]
Framework Design Guidelines 3.1.2 would argue for "Aws", though Brad Abrams suggests making an exception for trademarks.
