### ISSUE TITLE
Improve and check the getting-started docs

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.AWS#4]
The docs in the README.md are rudimentary. Some thoughts:
- [ ] Check and improve the deployment instructions
- [ ] Check and improve the build/test instructions
- [ ] Contribute docs to http://mbrace.io (e.g. make the docs be on-par with Azure?)

https://github.com/mbraceproject/MBrace.AWS/blob/master/README.md

**Comment by dsyme** [comment]
@AviAvni Thanks again for doing this!!

**Comment by dsyme** [comment]
@AviAvni If you would like to become a co-maintainer on MBrace.AWS please let me know (then you could have closed this issue too :) )

**Comment by AviAvni** [comment]
@dsyme thanks I would be happy to help

**Comment by dsyme** [comment]
@AviAvni OK, you now have maintainer access to MBrace.AWS :)
