### ISSUE TITLE
Upgrade to latest FSharp.AWS.DynamoDB

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.AWS#5]
I took a look around at what needs doing here and noticed that FSharp.AWS.DynamoDB is not at its latest version

https://github.com/mbraceproject/MBrace.AWS/blob/master/paket.lock#L15

https://www.nuget.org/packages/FSharp.AWS.DynamoDB/

**Comment by AviAvni** [comment]
@dsyme done

**Comment by dsyme** [comment]
@AviAvni I know this was some time ago, but thanks for doing this :)
